In [67]:
import os 
import sys 
import glob 
import re 
import nltk 
import string 
os.chdir(r'C:\Users\ADMIN\Documents\Nam_3\CS419\project')
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

from source.utils.textPreprocessing import TextPreprocessing
from source.utils.inverted_index import InvertedIndex
from source.utils.BM25_retriever import BM25Retriever
from source.utils.evaluations import Evaluator

pd.set_option('display.max_rows', 1000)
pd.set_option("max_colwidth", 40)

In [68]:
docs_path = r'C:\Users\ADMIN\Documents\Nam_3\CS419\project\data\medline\new_version\new_medline_docs.csv'
queries_path = r'C:\Users\ADMIN\Documents\Nam_3\CS419\project\data\medline\new_version\new_medline_queries.csv'
qrels_path = r'C:\Users\ADMIN\Documents\Nam_3\CS419\project\data\medline\new_version\new_medline_qrels.csv'

medline_docs_df = pd.read_csv(docs_path)
medline_queries_df = pd.read_csv(queries_path)
medline_qrels_df = pd.read_csv(qrels_path)

docs_df = medline_docs_df[['doc_id', 'doc_text']] 
queries_df = medline_queries_df[['query_id', 'query_text']]

In [69]:
docs_df.rename(columns={'doc_id':'id', 'doc_text':'content'}, inplace=True) 
queries_df.rename(columns={'query_id':'id', 'query_text':'content'}, inplace=True)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_19212\4133813531.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  docs_df.rename(columns={'doc_id':'id', 'doc_text':'content'}, inplace=True)
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_19212\4133813531.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  queries_df.rename(columns={'query_id':'id', 'query_text':'content'}, inplace=True)

In [70]:
docs_df.head()

         id                                  content
0  10793663  The influence of subcellular fractio...
1  10793671  Temperature sensitive mutants of Esc...
2  11370242  Differences in sensitivity to nerve ...
3  11712291       Susceptibility to rheumatic fever.
4  11894928  Fusion of DNA region to murine immun...

In [71]:
queries_df.head()

   id                                  content
0   1  Ferroportin-1 in humans Find article...
1   2  Generating transgenic mice Find prot...
2   3  Time course for gene expression in m...
3   4  Gene expression profiles for kidney ...
4   5  Protocols for isolating cell nuclei ...

In [72]:
tp = TextPreprocessing() 
processed_docs = tp.process_dataframe(dataframe=docs_df) 
processed_docs

,id,content,tokens
0,10793663,The influence of subcellular fractio...,"(influence, subcellular, fraction, e..."
1,10793671,Temperature sensitive mutants of Esc...,"(temperature, sensitive, mutant, esc..."
2,11370242,Differences in sensitivity to nerve ...,"(difference, sensitivity, nerve, gro..."
3,11712291,Susceptibility to rheumatic fever.,"(susceptibility, rheumatic, fever)"
4,11894928,Fusion of DNA region to murine immun...,"(fusion, dna, region, murine, immuno..."
...,...,...,...
16211,11716567,Cerebrospinal fluid amyloid beta(1-4...,"(cerebrospinal, fluid, amyloid, beta..."
16212,10565364,Technical aspects of central venous ...,"(technical, aspect, central, venous,..."
16213,12115947,New evidence for a presynaptic actio...,"(new, evidence, presynaptic, action,..."
16214,9203220,Confirmation of fetal aneuploidy wit...,"(confirmation, fetal, aneuploidy, pr..."
16215,10826929,Dependence of electrogram duration i...,"(dependence, electrogram, duration, ..."

In [73]:
vocab = tp.get_vocab() 
print(vocab[:50])

['aa', 'aaa', 'aaaa', 'aaaaaccgc', 'aaag', 'aab', 'aac', 'aact', 'aad', 'aadc', 'aade', 'aae', 'aaf', 'aag', 'aagg', 'aaha', 'aahanet', 'aalatg', 'aalpha', 'aamp', 'aana', 'aanat', 'aao', 'aaohn', 'aap', 'aaph', 'aaps', 'aartsma', 'aasld', 'aat', 'aatt', 'aav', 'ab', 'aba', 'ababa', 'abagyan', 'abandon', 'abandoned', 'abandonment', 'abarrent', 'abasic', 'abate', 'abattoir', 'abaxial', 'abbott', 'abbreviated', 'abc', 'abcdefg', 'abciximab', 'abd']

In [74]:
index = InvertedIndex(processed_docs, vocab)
index._build()

In [75]:
bm25 = BM25Retriever(processed_docs, index)

In [76]:
sample_queries = queries_df.head(5).to_dict(orient="records")
results = []
for row in sample_queries:
    qid = row["id"]
    query_text = row["content"]
    hits = bm25.search(query_text, top_k=30)
    results.append({"qid": qid, "query": query_text, "top5": hits})

results_df = pd.DataFrame(results)
results_df

,qid,query,top5
0,1,Ferroportin-1 in humans Find article...,"[(11313311, 113.65429461293166), (11..."
1,2,Generating transgenic mice Find prot...,"[(10949829, 67.02586587888412), (123..."
2,3,Time course for gene expression in m...,"[(9726250, 47.62551723466797), (1191..."
3,4,Gene expression profiles for kidney ...,"[(12089378, 50.7524681871178), (1208..."
4,5,Protocols for isolating cell nuclei ...,"[(9527488, 32.60212525312107), (1060..."

In [77]:
queries_records = queries_df.to_dict(orient="records")
qrels = medline_qrels_df.to_dict(orient='records')

In [78]:
def build_qrels_dict(qrels_records):
    qrels_dict = {}

    for row in qrels_records:
        qid = row.get("query_id") or row.get("qid")
        did = row.get("doc_id") or row.get("docid") or row.get("document_id")
        rel = row.get("relevance") or row.get("rel") or row.get("score")

        qrels_dict.setdefault(qid, {})[did] = float(rel)

    return qrels_dict


qrels = build_qrels_dict(qrels)

In [79]:
k = 25

bm25_evaluator = Evaluator(
    queries=queries_records,
    qrels=qrels,
    retriever=bm25,
    normalize_relevance_scores=True,
)

result = bm25_evaluator.evaluate_all(top_k=k, return_results=True, return_df=True)
metrics = result.summary

metrics

{'Precision@25': 0.6607999999999999,
 'Recall@25': 0.27242191135730787,
 'F1@25': 0.3007256484155043,
 'MAP@25': 0.6384820099128112,
 'Ndcg@25': 0.4526754357152083}

In [80]:
summary_df = result.summary_df
display(summary_df)

   Precision@25  Recall@25     F1@25    MAP@25   Ndcg@25
0        0.6608   0.272422  0.300726  0.638482  0.452675

In [81]:
per_query_df = result.per_query_df
display(per_query_df)

,precision,recall,f1,ap,ndcg,hit,rr,relevant_count,retrieved_count,hit_count,has_relevance
query_id,,,,,,,,,,,
1,0.96,0.585366,0.727273,0.890695,0.557795,1.0,1.000000,41.0,25.0,24.0,1.0
2,0.92,0.353846,0.511111,0.902657,0.657371,1.0,1.000000,65.0,25.0,23.0,1.0
3,1.00,0.193798,0.324675,1.000000,0.519975,1.0,1.000000,129.0,25.0,25.0,1.0
4,0.12,0.150000,0.133333,0.023750,0.121227,1.0,0.200000,20.0,25.0,3.0,1.0
5,0.28,0.437500,0.341463,0.229341,0.471501,1.0,1.000000,16.0,25.0,7.0,1.0
6,0.64,0.275862,0.385542,0.450168,0.391852,1.0,1.000000,58.0,25.0,16.0,1.0
7,0.96,0.307692,0.466019,0.954994,0.459932,1.0,1.000000,78.0,25.0,24.0,1.0
8,0.72,0.157895,0.258993,0.547787,0.363484,1.0,1.000000,114.0,25.0,18.0,1.0
9,1.00,0.304878,0.467290,1.000000,0.613488,1.0,1.000000,82.0,25.0,25.0,1.0
10,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2.0,25.0,0.0,1.0
11,0.80,0.227273,0.353982,0.697771,0.413763,1.0,1.000000,88.0,25.0,20.0,1.0
12,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,182.0,25.0,0.0,1.0
13,0.36,0.450000,0.400000,0.325298,0.442724,1.0,1.000000,20.0,25.0,9.0,1.0
14,0.24,0.333333,0.279070,0.262037,0.425291,1.0,1.000000,18.0,25.0,6.0,1.0
15,0.68,0.265625,0.382022,0.523410,0.368242,1.0,1.000000,64.0,25.0,17.0,1.0
16,1.00,0.227273,0.370370,1.000000,0.400775,1.0,1.000000,110.0,25.0,25.0,1.0
17,0.04,1.000000,0.076923,0.047619,0.224244,1.0,0.047619,1.0,25.0,1.0,1.0
18,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.0,25.0,0.0,1.0
19,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.0,25.0,0.0,1.0
20,0.92,0.298701,0.450980,0.867452,0.473281,1.0,1.000000,77.0,25.0,23.0,1.0
21,0.08,0.038462,0.051948,0.005636,0.036518,1.0,0.050000,52.0,25.0,2.0,1.0
22,0.80,0.121951,0.211640,0.684355,0.463218,1.0,1.000000,164.0,25.0,20.0,1.0
23,1.00,0.201613,0.335570,1.000000,0.460696,1.0,1.000000,124.0,25.0,25.0,1.0
24,0.56,0.933333,0.700000,0.933333,0.926730,1.0,1.000000,15.0,25.0,14.0,1.0
25,0.64,0.800000,0.711111,0.650968,0.729431,1.0,1.000000,20.0,25.0,16.0,1.0
26,0.12,0.088235,0.101695,0.075897,0.109900,1.0,1.000000,34.0,25.0,3.0,1.0
27,0.72,0.750000,0.734694,0.737659,0.530114,1.0,1.000000,24.0,25.0,18.0,1.0
28,0.28,1.000000,0.437500,0.437554,0.531368,1.0,0.500000,7.0,25.0,7.0,1.0
29,1.00,0.781250,0.877193,1.000000,0.623096,1.0,1.000000,32.0,25.0,25.0,1.0
30,1.00,0.198413,0.331126,1.000000,0.543498,1.0,1.000000,126.0,25.0,25.0,1.0
31,1.00,0.245098,0.393701,1.000000,1.000000,1.0,1.000000,102.0,25.0,25.0,1.0
32,1.00,0.067568,0.126582,1.000000,0.376692,1.0,1.000000,370.0,25.0,25.0,1.0
33,0.88,0.423077,0.571429,0.863489,0.510932,1.0,1.000000,52.0,25.0,22.0,1.0
34,0.92,0.884615,0.901961,0.872676,0.897538,1.0,1.000000,26.0,25.0,23.0,1.0
35,0.84,0.102941,0.183406,0.722402,0.401073,1.0,1.000000,204.0,25.0,21.0,1.0
36,0.16,0.018182,0.032653,0.058222,0.060605,1.0,0.333333,220.0,25.0,4.0,1.0
37,1.00,0.195312,0.326797,1.000000,0.499134,1.0,1.000000,128.0,25.0,25.0,1.0
38,1.00,0.082237,0.151976,1.000000,0.518410,1.0,1.000000,304.0,25.0,25.0,1.0
39,0.92,0.099138,0.178988,0.901756,0.598653,1.0,1.000000,232.0,25.0,23.0,1.0
40,1.00,0.110132,0.198413,1.000000,0.697714,1.0,1.000000,227.0,25.0,25.0,1.0
41,1.00,0.051975,0.098814,1.000000,0.633256,1.0,1.000000,481.0,25.0,25.0,1.0
42,1.00,0.044170,0.084602,1.000000,0.903033,1.0,1.000000,566.0,25.0,25.0,1.0
43,0.72,0.117647,0.202247,0.697133,0.325806,1.0,1.000000,153.0,25.0,18.0,1.0
44,1.00,0.047259,0.090253,1.000000,0.365049,1.0,1.000000,529.0,25.0,25.0,1.0
45,0.52,0.111111,0.183099,0.381554,0.374008,1.0,1.000000,117.0,25.0,13.0,1.0
46,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,144.0,25.0,0.0,1.0
47,1.00,0.098039,0.178571,1.000000,0.873679,1.0,1.000000,255.0,25.0,25.0,1.0
48,1.00,0.227273,0.370370,1.000000,0.719372,1.0,1.000000,110.0,25.0,25.0,1.0
49,0.24,0.105263,0.146341,0.178485,0.174119,1.0,1.000000,57.0,25.0,6.0,1.0
50,1.00,0.107759,0.194553,1.000000,0.845184,1.0,1.000000,232.0,25.0,25.0,1.0